apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  DB_USER: bXl1c2Vy     # base64 encoded for "myuser"
  DB_PASS: cGFzc3dvcmQ= # base64 encoded for "password"

