apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data   # Node ke local path ko use kar raha hai

